### ISSUE TITLE
Cleanup Package Vars files with a Dictionary Structure

### ISSUE THREAD

**Issue by billwheatley** [billwheatley/provision-desktop#47]
For OS specific packages names make one dictionary object that you have a parent package name with possible alternate names if the name varies between OS package managers. 

Benefits:
 - Allow easily adding other package mangers as well.
 - Make sure the vars are in sync (or it's obvious) between the OS'es
 - Could help with Issue #6 (make playbooks more flexible amount env types)
 - Address some of the nuances between: PopOs vs Ubuntu and Fedora vs RHEL

See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dict_lookup.html

Possible Example (will probably need to play around with this):
```yaml
packages:
  - name: Gimp
    package: 
      - gimp
        - ubuntu
        - redhat
    requires_gui: true

  - name: Open JDK
    package:
      - java-latest-openjdk
        - redhat
      - java-latest-openjdk-headless
        - redhat
      - openjdk-11-jdk
        - ubuntu
    requires_gui: false
```
