### ISSUE TITLE
Add deb and rpm URL installs

### ISSUE THREAD

**Issue by billwheatley** [billwheatley/provision-desktop#66]
Add a generic capability to install a list of URLs that contain direct downloads for debs or rpms.  First use case is zoom, which will fix issue #62 

Examples module usage: 

```yaml
- name: Install a .deb package from the internet.
  apt:
    deb: https://example.com/python-ppq_0.1-1_all.deb

- name: install the nginx rpm from a remote repo
  dnf:
    name: 'http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm'
    state: present
```
